Repository AOMediaCodec/av1-isobmff, pull requests merged in 2018-08, with the labels that each got.

#84 Rephrase introduction regarding support for scalability
  index.bs
  index.html
Labels: editorial

#86 introduce grouping_type_parameter for AV1MetadataSampleGroupEntry
  index.bs
  index.html
Labels: cr_technical

#89 rephrase note regarding mdcv and clli
  index.bs
  index.html
Labels: editorial

#90 clarify that Frame Header OBUs are not encrypted in Frame OBUs and other OBU/subsample aspects
  index.bs
  index.html
Labels: cr_technical, editorial

#91 Remove obsolete encryption figures.
  images/subsample-encryption-no-type.svg
  images/subsample-encryption-type.svg
  index.bs
  index.html
Labels: editorial

#92 rephrase cbcs requirements based on CENC recommendation
  index.bs
  index.html
Labels: editorial

#94 Fix external links.
  biblio.json
  index.bs
  index.html
Labels: editorial

#98 CodecWG comments
  index.bs
  index.html
Labels: editorial
